apiVersion: batch/v1
kind: CronJob
metadata:
  name: analytics
  namespace: protego-hw
spec:
  schedule: "10 0 */2 * *"  # Run at 00:10 every 2 days
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: analytics
            image: protego-hw-analytics:latest
            imagePullPolicy: IfNotPresent
            env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: protego-hw-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: protego-hw-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: protego-hw-config
                  key: POSTGRES_DB
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: protego-hw-config
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: protego-hw-config
                  key: POSTGRES_PORT
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: protego-hw-config
                  key: LOG_LEVEL
            resources:
              requests:
                memory: "256Mi"
                cpu: "200m"
              limits:
                memory: "1Gi"
                cpu: "500m"
          restartPolicy: OnFailure
