apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: protego-hw

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - postgres-pvc.yaml
  - postgres-deployment.yaml
  - postgres-service.yaml
  - api-deployment.yaml
  - api-service.yaml
  - api-ingress.yaml
  - scraper-cronjob.yaml
  - analytics-cronjob.yaml
