"""Add foreign key relationship between Drug and DrugClass

Revision ID: 0d3d27e2fd9f
Revises: 5d0cab0b26ec
Create Date: 2025-04-26 12:29:40.893195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d3d27e2fd9f'
down_revision: Union[str, None] = '5d0cab0b26ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drugs', sa.Column('drug_class_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'drugs', 'drug_classes_urls', ['drug_class_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'drugs', type_='foreignkey')
    op.drop_column('drugs', 'drug_class_id')
    # ### end Alembic commands ###
