"""Add analyzed column to DrugClass model

Revision ID: 4946f7590e8f
Revises: fb7e77f41cb1
Create Date: 2025-04-25 00:26:35.240290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4946f7590e8f'
down_revision: Union[str, None] = 'fb7e77f41cb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drug_classes_urls', sa.Column('analyzed', sa.Boolean(), nullable=True))
    op.drop_column('drug_classes_urls', 'is_analyzed')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drug_classes_urls', sa.Column('is_analyzed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('drug_classes_urls', 'analyzed')
    # ### end Alembic commands ###
